version: '3.8'

services:
  mysql:
    container_name: mysql_local
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
#      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=use_local
      - MYSQL_PASSWORD=local1234
      - MYSQL_ROOT_PASSWORD=local1234
      - TZ=Asia/Seoul